# -----------------------------------------------------------------------------
# Build workflow for portable apps
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.11.0
# -----------------------------------------------------------------------------
name: build-linux

on:
  workflow_dispatch:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master
    - main

jobs:
  build-linux:
    if: endsWith(github.repository, 'Portable')
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: uroesch/pa-wine:latest
      env:
        RUN_AS_ROOT: yes
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run build script via docker
      shell: bash
      run: |
        /entrypoint.sh \
          /usr/bin/pwsh -ExecutionPolicy ByPass \
          Other/Update/Update.ps1 -InfraDir /pa-build
      timeout-minutes: 10

    - name: Run script
      shell: bash
      run: |
        #ls -lh /pa-build
        mkdir -p /artifacts
        ls -lh /__w/
        find /__w/ \
        -type f \
        -name "*.paf.exe" \
        -exec cp {} /artifacts \;
        # /__w/xxxx

        exit 0

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: /artifacts